onboarding = false

[update]
channel = "stable"
version_check = true
manifest_check = true

[theme]
name = "kanagawa"

[ui.toast]
delivery = "system"

[ui]
agent_panel_sort = "priority"
show_agent_labels_on_pane_borders = true

[keys]
prefix = "f12"

[[keys.command]]
key = "f5"
type = "shell"
command = "herdr server reload-config"
description = "reload config"
